# Generated by Django 5.1.4 on 2024-12-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                blank=True,
                help_text="Укажи телегу",
                max_length=50,
                null=True,
                verbose_name="Телега ник",
            ),
        ),
    ]
